### ISSUE TITLE
Got an unexpected keyword argument 'max_iter' in SGDClassifier

### ISSUE THREAD

**Issue by tobegit3hub** [ClimbsRocks/auto_ml#328]
Fail to run the example in README.

```
from auto_ml import Predictor
from auto_ml.utils import get_boston_dataset

df_train, df_test = get_boston_dataset()

column_descriptions = {
    'MEDV': 'output'
    , 'CHAS': 'categorical'
}

ml_predictor = Predictor(type_of_estimator='regressor', column_descriptions=column_descriptions)

ml_predictor.train(df_train)

ml_predictor.score(df_test, df_test.MEDV)
```

And here is the error message.

```
➜ python ./automl_demo.py
Using TensorFlow backend.
Welcome to auto_ml! We're about to go through and make sense of your data using machine learning, and give you a production-ready pipeline to get predictions with.

If you have any issues, or new feature ideas, let us know at https://github.com/ClimbsRocks/auto_ml
Now using the model training_params that you passed in:
{}
After overwriting our defaults with your values, here are the final params that will be used to initialize the model:
{'presort': False, 'warm_start': True, 'learning_rate': 0.1}
Traceback (most recent call last):
  File "./automl_demo.py", line 13, in <module>
    ml_predictor.train(df_train)
  File "/usr/local/lib/python2.7/site-packages/auto_ml/predictor.py", line 611, in train
    X_df = self.fit_transformation_pipeline(X_df, y, estimator_names)
  File "/usr/local/lib/python2.7/site-packages/auto_ml/predictor.py", line 834, in fit_transformation_pipeline
    ppl = self._construct_pipeline(model_name=model_names[0], keep_cat_features=self.keep_cat_features)
  File "/usr/local/lib/python2.7/site-packages/auto_ml/predictor.py", line 206, in _construct_pipeline
    final_model = utils_models.get_model_from_name(model_name, training_params=params)
  File "/usr/local/lib/python2.7/site-packages/auto_ml/utils_models.py", line 129, in get_model_from_name
    'SGDClassifier': SGDClassifier(max_iter=1000, tol=0.001),
TypeError: __init__() got an unexpected keyword argument 'max_iter'
```

**Comment by doughng** [comment]
I'm experiencing same with the example in the README. 
My config: MacOS X  Anaconda Python 3.5.3

**Comment by ClimbsRocks** [comment]
It's almost certainly a scikit-learn version issue. try upgrading your scikit-learn version to 0.19.0. they started throwing a bunch of aggressive user warnings when not passing in those params in 0.19. i didn't realize that they would throw errors under older versions.

**Comment by ClimbsRocks** [comment]
i'll also try to make auto_ml more flexible so it can handle either version of sklearn. thanks for filing this!

**Comment by doughng** [comment]
Upgrading scikit-learn to 0.19.0 fixed my issue.

**Comment by tobegit3hub** [comment]
Thanks @ClimbsRocks and @doughng . It works after upgrading `scikit-learn`.

It would be much better to mention this in README or add the new version  as python dependency.

**Comment by ClimbsRocks** [comment]
it should be fixed in the latest release! thanks for filing the issue, y'all.

**Comment by sushant-singh01** [comment]
Hi, I am getting similar error for pre_dispatch only when I set optimize_final_model=True in ml_predictor.train(). It works fine when optimize_final_model=False. Below are the parameters I have given for my training.

```
model_names_list = ['GradientBoostingRegressor', 'LinearRegression', 'RandomForestRegressor', 'XGBRegressor']

ml_predictor.train(raw_training_data=df_train, optimize_final_model=True, perform_feature_selection=True, verbose=True, 
                   ml_for_analytics=True, take_log_of_y=None, model_names=model_names_list, 
                   perform_feature_scaling=True, calibrate_final_model=df_test, verify_features=True, cv=2, 
                   feature_learning=False, fl_data=None, prediction_intervals=True, compare_all_models=True)
```

Error Message:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-55-2e70efef7535> in <module>
      2                    ml_for_analytics=True, take_log_of_y=None, model_names=model_names_list,
      3                    perform_feature_scaling=True, calibrate_final_model=df_test, verify_features=True, cv=2,
----> 4                    feature_learning=False, fl_data=None, prediction_intervals=True, compare_all_models=True)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\automl-2.9.9-py3.6.egg\auto_ml\predictor.py in train(***failed resolving arguments***)
    664 
    665         # This is our main logic for how we train the final model
--> 666         self.trained_final_model = self.train_ml_estimator(self.model_names, self._scorer, X_df, y)
    667 
    668         if self.ensemble_config is not None and len(self.ensemble_config) > 0:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\automl-2.9.9-py3.6.egg\auto_ml\predictor.py in train_ml_estimator(self, estimator_names, scoring, X_df, y, feature_learning, prediction_interval)
   1263                 self.grid_search_params = grid_search_params
   1264 
-> 1265                 gscv_results = self.fit_grid_search(X_df, y, grid_search_params, feature_learning=feature_learning)
   1266 
   1267                 all_gs_results.append(gscv_results)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\automl-2.9.9-py3.6.egg\auto_ml\predictor.py in fit_grid_search(self, X_df, y, gs_params, feature_learning, refit)
   1150                 generations_number=generations_number,
   1151                 # Do not fit the best estimator on all the data- we will do that later, possibly after increasing epochs or n_estimators
-> 1152                 refit=refit
   1153 
   1154             )

TypeError: __init__() got an unexpected keyword argument 'pre_dispatch'
```

I, then tried to upgrade the sklearn version from 0.19.2 -> 0.20.0 as suggested above but then I started getting another error as mentioned below:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-65-2e70efef7535> in <module>
      2                    ml_for_analytics=True, take_log_of_y=None, model_names=model_names_list,
      3                    perform_feature_scaling=True, calibrate_final_model=df_test, verify_features=True, cv=2,
----> 4                    feature_learning=False, fl_data=None, prediction_intervals=True, compare_all_models=True)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\automl-2.9.9-py3.6.egg\auto_ml\predictor.py in train(***failed resolving arguments***)
    660 
    661         # This is our main logic for how we train the final model
--> 662         self.trained_final_model = self.train_ml_estimator(self.model_names, self._scorer, X_df, y)
    663 
    664         if self.ensemble_config is not None and len(self.ensemble_config) > 0:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\automl-2.9.9-py3.6.egg\auto_ml\predictor.py in train_ml_estimator(self, estimator_names, scoring, X_df, y, feature_learning, prediction_interval)
   1259                 self.grid_search_params = grid_search_params
   1260 
-> 1261                 gscv_results = self.fit_grid_search(X_df, y, grid_search_params, feature_learning=feature_learning)
   1262 
   1263                 all_gs_results.append(gscv_results)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\automl-2.9.9-py3.6.egg\auto_ml\predictor.py in fit_grid_search(self, X_df, y, gs_params, feature_learning, refit)
   1146                 generations_number=generations_number,
   1147                 # Do not fit the best estimator on all the data- we will do that later, possibly after increasing epochs or n_estimators
-> 1148                 refit=refit
   1149 
   1150             )

TypeError: Can't instantiate abstract class EvolutionaryAlgorithmSearchCV with abstract methods _run_search
```

After that, I tried to solve the problem as suggested [here](https://www.kaggle.com/c/home-credit-default-risk/discussion/64004) by adding below code in predictor.py and restarted the kernel.

```
# include below until https://github.com/scikit-optimize/scikit-optimize/issues/718 is resolved
class EvolutionaryAlgorithmSearchCV(EvolutionaryAlgorithmSearchCV):
    def _run_search(self, x): raise BaseException('Use newer skopt')
```

The original error is now popping up again & this time on sklearn.__version__ = 0.20.0.
Kindly advise.

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-57-2e70efef7535> in <module>
      2                    ml_for_analytics=True, take_log_of_y=None, model_names=model_names_list,
      3                    perform_feature_scaling=True, calibrate_final_model=df_test, verify_features=True, cv=2,
----> 4                    feature_learning=False, fl_data=None, prediction_intervals=True, compare_all_models=True)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\automl-2.9.9-py3.6.egg\auto_ml\predictor.py in train(***failed resolving arguments***)
    664 
    665         # This is our main logic for how we train the final model
--> 666         self.trained_final_model = self.train_ml_estimator(self.model_names, self._scorer, X_df, y)
    667 
    668         if self.ensemble_config is not None and len(self.ensemble_config) > 0:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\automl-2.9.9-py3.6.egg\auto_ml\predictor.py in train_ml_estimator(self, estimator_names, scoring, X_df, y, feature_learning, prediction_interval)
   1263                 self.grid_search_params = grid_search_params
   1264 
-> 1265                 gscv_results = self.fit_grid_search(X_df, y, grid_search_params, feature_learning=feature_learning)
   1266 
   1267                 all_gs_results.append(gscv_results)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\automl-2.9.9-py3.6.egg\auto_ml\predictor.py in fit_grid_search(self, X_df, y, gs_params, feature_learning, refit)
   1150                 generations_number=generations_number,
   1151                 # Do not fit the best estimator on all the data- we will do that later, possibly after increasing epochs or n_estimators
-> 1152                 refit=refit
   1153 
   1154             )

TypeError: __init__() got an unexpected keyword argument 'pre_dispatch'
``` 
#https://github.com/ClimbsRocks/auto_ml/issues/328#issuecomment-332285160
@ClimbsRocks
