### ISSUE TITLE
Error when using categorical ensemble

### ISSUE THREAD

**Issue by DVassilev** [ClimbsRocks/auto_ml#331]
Trying to use this based on the documentation and ran some test data but keep getting this error:
```
********************************************************************************************
About to fit the pipeline for the model GradientBoostingRegressor to predict Price
Started at:
2017-09-26 14:52:04
[1] random_holdout_set_from_training_data's score is: -17.88
multiprocess.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/anaconda/envs/py35/lib/python3.5/site-packages/multiprocess/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/anaconda/envs/py35/lib/python3.5/site-packages/multiprocess/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/anaconda/envs/py35/lib/python3.5/site-packages/pathos/helpers/mp_helper.py", line 15, in <lambda>
    func = lambda args: f(*args)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/auto_ml/predictor.py", line 1402, in <lambda>
    results = list(pool.map(lambda x: train_one_categorical_model(x[0], x[1], x[2]), categories_and_data))
  File "/anaconda/envs/py35/lib/python3.5/site-packages/auto_ml/predictor.py", line 1362, in train_one_categorical_model
    category_trained_final_model = self.train_ml_estimator(self.model_names, self._scorer, relevant_X, relevant_y)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/auto_ml/predictor.py", line 1158, in train_ml_estimator
    trained_final_model = self.fit_single_pipeline(X_df, y, estimator_names[0], feature_learning=feature_learning, prediction_interval=False)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/auto_ml/predictor.py", line 834, in fit_single_pipeline
    ppl.fit(X_df, y)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/auto_ml/utils_model_training.py", line 224, in fit
    self.model.fit(X_fit, y)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/sklearn/ensemble/gradient_boosting.py", line 1007, in fit
    y_pred = self._decision_function(X)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/sklearn/ensemble/gradient_boosting.py", line 1125, in _decision_function
    predict_stages(self.estimators_, X, self.learning_rate, score)
TypeError: Argument 'X' has incorrect type (expected numpy.ndarray, got csr_matrix)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 33, in <module>
    ml_predictor.train_categorical_ensemble(df_train, categorical_column = 'FuelCode')
  File "/anaconda/envs/py35/lib/python3.5/site-packages/auto_ml/predictor.py", line 1402, in train_categorical_ensemble
    results = list(pool.map(lambda x: train_one_categorical_model(x[0], x[1], x[2]), categories_and_data))
  File "/anaconda/envs/py35/lib/python3.5/site-packages/pathos/multiprocessing.py", line 137, in map
    return _pool.map(star(f), zip(*args)) # chunksize
  File "/anaconda/envs/py35/lib/python3.5/site-packages/multiprocess/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/anaconda/envs/py35/lib/python3.5/site-packages/multiprocess/pool.py", line 608, in get
    raise self._value
TypeError: Argument 'X' has incorrect type (expected numpy.ndarray, got csr_matrix)
```

This is the code that is being run:
```python
from auto_ml import Predictor
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

df = pd.read_excel('/home/ubuntu/formatted.xlsx')

df_train, df_test = train_test_split(
        df, test_size=0.15, random_state=42)

column_descriptions = {
        'Name' : 'categorical',
        'Address' : 'ignore',
        'Suburb' : 'ignore',
        'Postcode' : 'categorical',
        'Brand' : 'categorical',
        'Code': 'categorical',
        'PriceUpdatedDate' : 'date',
        'Price' : 'output' 
}
ml_predictor = Predictor(type_of_estimator='regressor', column_descriptions=column_descriptions)

ml_predictor.train_categorical_ensemble(df_train, categorical_column = 'Code')

ml_predictor.save(file_name='auto_ml_saved_pipeline.pkl', verbose=True)

test_score = ml_predictor.score(df_test, df_test.MEDV)
print(test_score)
```

Any suggestions on what me be the problem?

**Comment by DVassilev** [comment]
Had to update scikit-learn from 0.18.1 to 0.19.0 and it fixed it.

**Comment by ClimbsRocks** [comment]
ugh, data type issues. our transformation pipeline tries to use scipy.sparse matrices by default (more memory efficient, obviously), but makes datasets dense if it has to. sklearn was weird about what datasets you could use with gradientboosting (you could train on sparse, but not predict on sparse, if i recall). i thought i'd handled all of those edge cases, and had been using this functionality myself for a while, so i'm a bit surprised to see it rearing it's ugly head again. 

thanks for filing the issue! would love to hear anything else you encounter as you work with auto_ml more, or any ideas you have. and of course, pull requests (particularly on documentation) are super welcomed!
