### ISSUE TITLE
"optimize_final_model=True" fails !!

### ISSUE THREAD

**Issue by AshwiniBaipadithayaMadhusudan** [ClimbsRocks/auto_ml#421]
Hi,

I have been trying to train XGBClassifier on a data set containing around 750 data points.

Below is the code that i have used:
**ml_predictor.train(raw_training_data=df_train, perform_feature_selection=False, model_names=XGBClassifier,cv=2,perform_feature_scaling=False, feature_learning=True, fl_data=df_feature_learn,optimize_final_model=True)**

The above code runs fine if i set optimize_final_model=False.

But i am getting the below error when optimize_final_model=True.

[I 12:42:22.873 NotebookApp] Saving file at /automl/MAIN.ipynb
Process SpawnPoolWorker-10:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 337, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'Individual' on <module 'deap.creator' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\deap\\creator.py'>

Could anyone please suggest how to tackle this.

**Comment by csegerie** [comment]
I have the same issue
