### ISSUE TITLE
Error installing auto_ml

### ISSUE THREAD

**Issue by kevinmyers** [ClimbsRocks/auto_ml#441]
I ran `pip install auto_ml` and got the following error:

```
Collecting auto_ml
  Using cached auto_ml-2.9.10-py2.py3-none-any.whl (71 kB)
Collecting dill<0.3,>=0.2.5 (from auto_ml)
  Using cached dill-0.2.9.tar.gz (150 kB)
  Preparing metadata (setup.py) ... done
Collecting h5py<3.0,>=2.7.0 (from auto_ml)
  Using cached h5py-2.10.0.tar.gz (301 kB)
  Preparing metadata (setup.py) ... done
Collecting lightgbm<2.1,>=2.0.11 (from auto_ml)
  Using cached lightgbm-2.0.12-py2.py3-none-macosx_10_9_x86_64.macosx_10_10_x86_64.macosx_10_11_x86_64.macosx_10_12_x86_64.whl (608 kB)
Requirement already satisfied: numpy<2.0,>=1.11.0 in /Users/kevinmyers/opt/anaconda3/envs/autoML_env/lib/python3.12/site-packages (from auto_ml) (1.26.3)
Collecting pandas<1.0,>=0.18.0 (from auto_ml)
  Using cached pandas-0.25.3.tar.gz (12.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      /private/var/folders/sl/jyxzdp856v70v9s_8s8mczbm0000gq/T/pip-install-3dl2_4_q/pandas_c166a2c24568445ab4fe6486781404a6/setup.py:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        import pkg_resources
      /private/var/folders/sl/jyxzdp856v70v9s_8s8mczbm0000gq/T/pip-install-3dl2_4_q/pandas_c166a2c24568445ab4fe6486781404a6/setup.py:489: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        LooseVersion(python_target) < "10.9"
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/sl/jyxzdp856v70v9s_8s8mczbm0000gq/T/pip-install-3dl2_4_q/pandas_c166a2c24568445ab4fe6486781404a6/setup.py", line 812, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/sl/jyxzdp856v70v9s_8s8mczbm0000gq/T/pip-install-3dl2_4_q/pandas_c166a2c24568445ab4fe6486781404a6/versioneer.py", line 1440, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/private/var/folders/sl/jyxzdp856v70v9s_8s8mczbm0000gq/T/pip-install-3dl2_4_q/pandas_c166a2c24568445ab4fe6486781404a6/versioneer.py", line 1369, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/sl/jyxzdp856v70v9s_8s8mczbm0000gq/T/pip-install-3dl2_4_q/pandas_c166a2c24568445ab4fe6486781404a6/versioneer.py", line 401, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I am using an Intel MacOS v13.6.1
I am running in a conda environment with the following packages installed:
`matplotlib v 3.8.2`
`scikit-learn 1.4.0`
`pandas 2.2.0`
`biopython 1.83`
`numpy 1.26.3`
`python 3.12.1`
`pip 23.3`

Not sure what to do. Any ideas?

**Comment by ruan-xf** [comment]
well, I'm also using Intel macos 13, with the requirement of pandas from auto-ml here:
```
Collecting pandas<1.0,>=0.18.0 (from auto_ml)
  Using cached pandas-0.25.3.tar.gz (12.6 MB)
```

check python version pandas supported in pypi: [pandas · PyPI](https://pypi.org/project/pandas/0.25.3/), at least py 3.8 is ok for this pandas.

switch to python 3.8 and installation is done with no more error, pandas version installed now is 2.0.3, so funny it is.
